### ISSUE TITLE
Getting "Page not found" error if i do page refresh at "https://chatflora.com/main"

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [Salty-Bear/project-Flora#1]
This can be fixed by creating a "_redirects" file.
<img width="1284" alt="Screenshot 2023-03-21 at 16 11 53" src="https://user-images.githubusercontent.com/68241942/226651721-b4d4ddc0-83ed-43b0-90c5-bd5c08822a1c.png">

**Comment by Salty-Bear** [comment]
tyvm this was kensar for real. it was working fine in local host
